// Centralized error code registry.
// Add new codes here and reference them across controllers/services.
// Naming convention: DOMAIN_OPERATION_STATUS or BUSINESS_RULE.

export enum ErrorCodes {
  // Generic
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMITED = 'RATE_LIMITED',
  ACCESS_DENIED = 'ACCESS_DENIED',

  // Auth / Identity
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_TOKEN_REQUIRED = 'AUTH_TOKEN_REQUIRED',
  INVALID_USER = 'INVALID_USER',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_INVALID = 'TOKEN_INVALID', // legacy synonym mapping
  ROLE_FORBIDDEN = 'ROLE_FORBIDDEN',
  SHOP_ACCESS_DENIED = 'SHOP_ACCESS_DENIED',

  // Shared / Domain rules
  MISSING_CONTEXT = 'MISSING_CONTEXT',
  PRODUCT_REQUIRED = 'PRODUCT_REQUIRED',
  PRODUCT_RESOLUTION_FAILED = 'PRODUCT_RESOLUTION_FAILED',
  PRODUCT_NOT_ASSIGNED = 'PRODUCT_NOT_ASSIGNED',
  NO_FIELDS = 'NO_FIELDS',

  // Transactions
  ANALYTICS_FAILURE = 'ANALYTICS_FAILURE',
  FARMER_TXN_LIST_FAILURE = 'FARMER_TXN_LIST_FAILURE',
  BUYER_TXN_LIST_FAILURE = 'BUYER_TXN_LIST_FAILURE',
  UPDATE_FAILED = 'UPDATE_FAILED',
  DELETE_FAILED = 'DELETE_FAILED',
  TRANSACTION_CONTEXT_REQUIRED = 'TRANSACTION_CONTEXT_REQUIRED',
  TRANSACTION_NO_FIELDS_TO_UPDATE = 'TRANSACTION_NO_FIELDS_TO_UPDATE',
  TRANSACTION_UPDATE_FAILED = 'TRANSACTION_UPDATE_FAILED',
  TRANSACTION_DELETE_FAILED = 'TRANSACTION_DELETE_FAILED',
  TRANSACTION_CREATE_FAILED = 'TRANSACTION_CREATE_FAILED',
  TRANSACTION_IDEMPOTENCY_CONFLICT = 'TRANSACTION_IDEMPOTENCY_CONFLICT',
  PRODUCT_NORMALIZATION_FAILED = 'PRODUCT_NORMALIZATION_FAILED',
  TRANSACTION_SETTLEMENT_GET_FAILED = 'TRANSACTION_SETTLEMENT_GET_FAILED',
  EXPENSE_OFFSET_FAILED = 'EXPENSE_OFFSET_FAILED',

  // Payments
  CREATE_PAYMENT_FAILED = 'CREATE_PAYMENT_FAILED',
  ALLOCATE_PAYMENT_FAILED = 'ALLOCATE_PAYMENT_FAILED',
  UPDATE_PAYMENT_STATUS_FAILED = 'UPDATE_PAYMENT_STATUS_FAILED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  GET_PAYMENTS_BY_TXN_FAILED = 'GET_PAYMENTS_BY_TXN_FAILED',
  GET_PAYMENTS_FARMER_FAILED = 'GET_PAYMENTS_FARMER_FAILED',
  GET_PAYMENTS_BUYER_FAILED = 'GET_PAYMENTS_BUYER_FAILED',
  CREATE_BULK_PAYMENTS_FAILED = 'CREATE_BULK_PAYMENTS_FAILED',
  GET_OUTSTANDING_PAYMENTS_FAILED = 'GET_OUTSTANDING_PAYMENTS_FAILED',

  // Credit / Advances
  ISSUE_CREDIT_FAILED = 'ISSUE_CREDIT_FAILED',
  REPAY_CREDIT_FAILED = 'REPAY_CREDIT_FAILED',

  // Shop Categories
  BULK_ASSIGN_FAILED = 'BULK_ASSIGN_FAILED',
  BULK_REMOVE_FAILED = 'BULK_REMOVE_FAILED',
  ASSIGN_SINGLE_FAILED = 'ASSIGN_SINGLE_FAILED',
  REMOVE_SINGLE_FAILED = 'REMOVE_SINGLE_FAILED',
  GET_SHOP_CATEGORIES_FAILED = 'GET_SHOP_CATEGORIES_FAILED',
  GET_CATEGORY_SHOPS_FAILED = 'GET_CATEGORY_SHOPS_FAILED',
  CHECK_ASSIGNMENT_FAILED = 'CHECK_ASSIGNMENT_FAILED',
  GET_ASSIGNMENTS_FAILED = 'GET_ASSIGNMENTS_FAILED',

  // Balance / Users / Shops
  SHOP_NOT_FOUND = 'SHOP_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  GET_BALANCE_FAILED = 'GET_BALANCE_FAILED',
  GET_SHOP_BALANCE_FAILED = 'GET_SHOP_BALANCE_FAILED',
  ADD_PAYMENT_FARMER_FAILED = 'ADD_PAYMENT_FARMER_FAILED',
  ADD_PAYMENT_BUYER_FAILED = 'ADD_PAYMENT_BUYER_FAILED',
  UPDATE_BALANCE_FAILED = 'UPDATE_BALANCE_FAILED',
  BALANCE_HISTORY_FAILED = 'BALANCE_HISTORY_FAILED',

  // Settlements
  FIFO_REPAY_FAILED = 'FIFO_REPAY_FAILED',
  GET_SETTLEMENTS_FAILED = 'GET_SETTLEMENTS_FAILED',
  CREATE_SETTLEMENT_FAILED = 'CREATE_SETTLEMENT_FAILED',
  GET_SETTLEMENT_FAILED = 'GET_SETTLEMENT_FAILED',
  UPDATE_SETTLEMENT_STATUS_FAILED = 'UPDATE_SETTLEMENT_STATUS_FAILED',
  GET_SETTLEMENT_SUMMARY_FAILED = 'GET_SETTLEMENT_SUMMARY_FAILED',
  SETTLE_AMOUNT_FAILED = 'SETTLE_AMOUNT_FAILED',
  CREATE_EXPENSE_FAILED = 'CREATE_EXPENSE_FAILED',

  // Commission / Fees
  COMMISSION_CALC_FAILED = 'COMMISSION_CALC_FAILED',
  CREATE_COMMISSION_FAILED = 'CREATE_COMMISSION_FAILED',
  GET_COMMISSIONS_FAILED = 'GET_COMMISSIONS_FAILED',
  UPDATE_COMMISSION_FAILED = 'UPDATE_COMMISSION_FAILED',
  COMMISSION_NOT_FOUND = 'COMMISSION_NOT_FOUND'

  ,// Plans
  CREATE_PLAN_FAILED = 'CREATE_PLAN_FAILED',
  GET_PLANS_FAILED = 'GET_PLANS_FAILED',
  GET_PLAN_FAILED = 'GET_PLAN_FAILED',
  UPDATE_PLAN_FAILED = 'UPDATE_PLAN_FAILED',
  DELETE_PLAN_FAILED = 'DELETE_PLAN_FAILED',
  DEACTIVATE_PLAN_FAILED = 'DEACTIVATE_PLAN_FAILED',
  SEARCH_PLANS_FAILED = 'SEARCH_PLANS_FAILED',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',

  // Categories
  CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED',
  GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED',
  GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED',
  UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED',
  DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED',
  DEACTIVATE_CATEGORY_FAILED = 'DEACTIVATE_CATEGORY_FAILED',
  SEARCH_CATEGORIES_FAILED = 'SEARCH_CATEGORIES_FAILED',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  // Products
  CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED',
  GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED',
  GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED',
  UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED',
  DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS'

  ,// Shops
  CREATE_SHOP_FAILED = 'CREATE_SHOP_FAILED',
  GET_SHOPS_FAILED = 'GET_SHOPS_FAILED',
  GET_SHOP_FAILED = 'GET_SHOP_FAILED',
  UPDATE_SHOP_FAILED = 'UPDATE_SHOP_FAILED',
  DELETE_SHOP_FAILED = 'DELETE_SHOP_FAILED',
  SHOP_NOT_FOUND_ERROR = 'SHOP_NOT_FOUND_ERROR', // distinct from SHOP_NOT_FOUND generic if needed
  GET_AVAILABLE_OWNERS_FAILED = 'GET_AVAILABLE_OWNERS_FAILED',

  // Reports
  REPORT_GENERATION_FAILED = 'REPORT_GENERATION_FAILED',
  REPORT_DOWNLOAD_FAILED = 'REPORT_DOWNLOAD_FAILED',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',

  // Shop Products (assignment)
  ASSIGN_PRODUCT_FAILED = 'ASSIGN_PRODUCT_FAILED',
  REMOVE_PRODUCT_FAILED = 'REMOVE_PRODUCT_FAILED',
  TOGGLE_PRODUCT_STATUS_FAILED = 'TOGGLE_PRODUCT_STATUS_FAILED',
  GET_SHOP_PRODUCTS_FAILED = 'GET_SHOP_PRODUCTS_FAILED',
  GET_AVAILABLE_PRODUCTS_FAILED = 'GET_AVAILABLE_PRODUCTS_FAILED',
  PRODUCT_MAPPING_NOT_FOUND = 'PRODUCT_MAPPING_NOT_FOUND',

  // Expenses
  GET_EXPENSES_FAILED = 'GET_EXPENSES_FAILED',
  GET_EXPENSE_FAILED = 'GET_EXPENSE_FAILED',
  UPDATE_EXPENSE_FAILED = 'UPDATE_EXPENSE_FAILED',
  DELETE_EXPENSE_FAILED = 'DELETE_EXPENSE_FAILED',
  GET_EXPENSE_SUMMARY_FAILED = 'GET_EXPENSE_SUMMARY_FAILED',
  EXPENSE_NOT_FOUND = 'EXPENSE_NOT_FOUND',
  GET_EXPENSE_ALLOCATION_FAILED = 'GET_EXPENSE_ALLOCATION_FAILED'
}

export type ErrorCode = `${ErrorCodes}`;
