import jsPDF from 'jspdf';

export interface PaymentLike {
  payer?: string;
  payee?: string;
  amount?: number | string;
  method?: string;
  payment_date?: string; // already formatted date string
}

export interface TransactionLike {
  id?: string | number;
  transaction_id?: string | number;
  created_at?: string;
  product_name?: string;
  buyer_name?: string;
  farmer_name?: string;
  total_sale_value?: number | string;
  buyer_paid?: number | string;
  deficit?: number | string; // buyer pending
  farmer_paid?: number | string;
  farmer_due?: number | string; // farmer pending
  payments?: PaymentLike[];
}

interface ExportOptions {
  title?: string;
  shopName?: string;
  dateRange?: { from?: string; to?: string };
  generatedBy?: string;
  ownerFirstName?: string;
  ownerUsername?: string;
}

const formatCurrency = (value: number | string | undefined) => {
  if (value === undefined || value === null || value === '') return 'Rs. 0';
  const num = typeof value === 'string' ? parseFloat(value) : value;
  if (isNaN(num)) return 'Rs. 0';
  return 'Rs. ' + num.toLocaleString('en-IN');
};

export function exportTransactionsPDF(transactions: TransactionLike[], options: ExportOptions = {}) {
  if (!transactions || transactions.length === 0) return;
  const doc = new jsPDF({ orientation: 'landscape' });
  let y = 14;

  // Header
  doc.setFontSize(14);
  doc.text(options.title || 'Transactions Report', 14, y);
  y += 6;
  doc.setFontSize(10);
  if (options.shopName) { doc.text(`Shop: ${options.shopName}`, 14, y); y += 5; }
  if (options.dateRange) {
    const dr = options.dateRange;
    if (dr.from || dr.to) { doc.text(`Period: ${dr.from || ''} to ${dr.to || ''}`, 14, y); y += 5; }
  }
  if (options.ownerFirstName || options.ownerUsername) {
    const ownerLabel = options.ownerFirstName ? options.ownerFirstName : options.ownerUsername;
    doc.text(`Generated By: ${ownerLabel}`, 14, y); y += 5;
  } else if (options.generatedBy) {
    doc.text(`Generated By: ${options.generatedBy}`, 14, y); y += 5;
  }
  // Summary totals
  const totals = transactions.reduce((acc, t) => {
    const toNum = (v: any) => { const n = typeof v === 'string' ? parseFloat(v) : v; return isNaN(n) ? 0 : n; };
    acc.total += toNum(t.total_sale_value);
    acc.buyerPaid += toNum(t.buyer_paid);
    acc.buyerPending += toNum(t.deficit);
    acc.farmerPaid += toNum(t.farmer_paid);
    acc.farmerPending += toNum(t.farmer_due);
    return acc;
  }, { total:0, buyerPaid:0, buyerPending:0, farmerPaid:0, farmerPending:0 });
  doc.setFont('helvetica', 'bold');
  doc.text(
    `Totals: Sale ${formatCurrency(totals.total)}`,
    14, y, { maxWidth: 260 }
  );
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Buyer Paid ${formatCurrency(totals.buyerPaid)} | Buyer Pending ${formatCurrency(totals.buyerPending)} | Farmer Paid ${formatCurrency(totals.farmerPaid)} | Farmer Pending ${formatCurrency(totals.farmerPending)}`,
    14, y + 5, { maxWidth: 260 }
  );
  y += 13;
  doc.setDrawColor(180); doc.line(10, y, 285, y); y += 6;

  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = 275; // landscape width minus margins
  const leftX = 14;

  const ensureSpace = (linesNeeded: number) => {
    if (y + linesNeeded > pageHeight - 12) {
      doc.addPage();
      y = 14;
      doc.setFontSize(12);
      doc.text('Transactions (cont.)', leftX, y); y += 6;
      doc.setDrawColor(180); doc.line(10, y, 285, y); y += 4;
      doc.setFontSize(10);
    }
  };

  transactions.forEach((t, index) => {
    ensureSpace(30); // rough reservation; will handle additional payments dynamically
  doc.setFontSize(11);
  const txId = t.transaction_id || t.id || index + 1;
  doc.setFont('helvetica', 'bold');
  doc.text(`Txn #${txId}`, leftX, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  if (t.created_at) doc.text(String(t.created_at), leftX + 35, y);
  y += 5;

  // Important info bold
  doc.setFont('helvetica', 'bold');
  doc.text(`Product: ${t.product_name || ''}`, leftX + 4, y);
  y += 5;
  doc.text(`Buyer: ${t.buyer_name || ''}`, leftX + 4, y);
  y += 5;
  doc.text(`Seller: ${t.farmer_name || ''}`, leftX + 4, y);
  y += 5;
  doc.text(`Total: ${formatCurrency(t.total_sale_value)}`, leftX + 4, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.text(`Buyer Paid: ${formatCurrency(t.buyer_paid)} | Buyer Pending: ${formatCurrency(t.deficit)}`, leftX + 4, y);
  y += 5;
  doc.text(`Farmer Paid: ${formatCurrency(t.farmer_paid)} | Farmer Pending: ${formatCurrency(t.farmer_due)}`, leftX + 4, y);
  y += 5;

    // Payments
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Payments:', leftX + 4, y); y += 5;
    doc.setFont('helvetica', 'normal');
    if (t.payments && t.payments.length) {
      t.payments.forEach((p) => {
        ensureSpace(6);
        const payer = p.payer || '';
        const payee = p.payee || '';
        const amount = formatCurrency(p.amount || 0);
        const method = p.method || '';
        const date = p.payment_date ? `, ${p.payment_date}` : '';
        // Bold amount only
        const prefix = `• ${payer} -> ${payee}: `;
        const suffix = ` (${method}${date})`;
        doc.setFont('helvetica', 'normal');
        const prefixWidth = doc.getTextWidth(prefix);
        const amountWidth = doc.getTextWidth(amount);
        const startX = leftX + 10;
        doc.text(prefix, startX, y);
        doc.setFont('helvetica', 'bold');
        doc.text(amount, startX + prefixWidth, y);
        doc.setFont('helvetica', 'normal');
        doc.text(suffix, startX + prefixWidth + amountWidth, y);
        y += 5;
      });
    } else {
      doc.text('No payments', leftX + 10, y); y += 5;
    }

    // Divider
    y += 2;
    doc.setDrawColor(230); doc.line(12, y, 283, y); y += 6;
  });

  doc.save('transactions.pdf');
}
