// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhpflrprylcszgfiqgky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpocGZscnByeWxjc3pnZmlxZ2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODk1NjgsImV4cCI6MjA3MjA2NTU2OH0.bEmOqV23Keem2btRWAg9bqGoiObtVUo4rCrxQ-QqYqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});